export const config = {
    coupleNames: process.env.NEXT_PUBLIC_COUPLE_NAMES || "Thắng & Hiền",
    eventDate: process.env.NEXT_PUBLIC_EVENT_DATE || "2026-01-18T11:00:00",
    groom: process.env.NEXT_PUBLIC_GROOM_NAME || "Đỗ Văn Thắng",
    groomNickName: process.env.NEXT_PUBLIC_GROOM_NICKNAME || "Stevendo",
    groomInstagram: process.env.NEXT_PUBLIC_GROOM_INSTAGRAM || "Facebook",
    groomBio: process.env.NEXT_PUBLIC_GROOM_BIO || "Đẹp trai thì dư nghề rồi",
    bride: process.env.NEXT_PUBLIC_BRIDE_NAME || "Ta Thu Hiền",
    brideNickName: process.env.NEXT_PUBLIC_BRIDE_NICKNAME || "Lucy",
    brideInstagram: process.env.NEXT_PUBLIC_BRIDE_INSTAGRAM || "Facebook",
    brideBio: process.env.NEXT_PUBLIC_BRIDE_BIO || "Mỏng như tờ giấy, yếu đuối như sương mai",
    bibleVerse: process.env.NEXT_PUBLIC_BIBLE_VERSE || "Hai trái tim, một nhịp đập",
    bibleVerseContent: process.env.NEXT_PUBLIC_BIBLE_VERSE_CONTENT || "cùng viết nên câu chuyện tình yêu",
    timeline_1: process.env.NEXT_PUBLIC_YEAR_1 || "14/2/2021",
    timeline_1_content: process.env.NEXT_PUBLIC_YEAR_1_CONTENT || "Năm 2021, chúng tôi bắt đầu hành trình của mình với tư cách là hai cá thể mới bắt đầu tìm hiểu nhau. Chúng tôi háo hức khám phá những gì tương lai mang lại và háo hức xem con đường của mình sẽ dẫn đến đâu.",
    timeline_2: process.env.NEXT_PUBLIC_YEAR_2 || "2023",
    timeline_2_content: process.env.NEXT_PUBLIC_YEAR_2_CONTENT || "Năm 2023, chúng tôi tiếp tục hành trình, đối mặt với nhiều thử thách và trở ngại trên đường đi. Chúng tôi đã học được cách giao tiếp hiệu quả và làm việc nhóm, và nhờ đó, mối quan hệ của chúng tôi ngày càng bền chặt hơn.",
    timeline_3: process.env.NEXT_PUBLIC_YEAR_3 || "2026",
    timeline_3_content: process.env.NEXT_PUBLIC_YEAR_3_CONTENT || "Và giờ đây, năm 2026, chúng tôi đã đạt đến đỉnh cao của hành trình – hôn nhân. Đó là một hành trình đầy niềm vui và thú vị, tràn ngập tiếng cười, tình yêu và vô vàn khả năng. Chúng tôi đã cùng nhau tạo nên vô vàn kỷ niệm, từ buổi hẹn hò đầu tiên đến lễ đính hôn, và giờ là ngày cưới. Hành trình của chúng tôi thật trọn vẹn, và chúng tôi trân trọng từng khoảnh khắc đã chia sẻ. Chúng tôi mong chờ được tiếp tục cuộc phiêu lưu của mình với tư cách là một cặp đôi đã kết hôn.",
    holyMatrimony: {
        enabled: process.env.NEXT_PUBLIC_HOLY_MATRIMONY === 'true',
        time: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_TIME || "00:00",
        place: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE || "Default Church",
        place_details: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_PLACE_DETAILS || "Default Street",
        googleMapsLink: process.env.NEXT_PUBLIC_HOLY_MATRIMONY_GOOGLE_MAPS || "https://maps.app.goo.gl/vPmfWux29qYYfkJTA",
    },
    weddingReception: {
        enabled: process.env.NEXT_PUBLIC_WEDDING_RECEPTION === 'true',
        time: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_TIME || "00:00",
        place: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE || "Default Venue",
        place_details: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_PLACE_DETAILS || "Default Street",
        googleMapsLink: process.env.NEXT_PUBLIC_WEDDING_RECEPTION_GOOGLE_MAPS || "https://maps.app.goo.gl/fQGiC37iEx6fcuNq8",
    },
    livestreaming: {
        enabled: process.env.NEXT_PUBLIC_LIVE_STREAMING === 'true',
        time: process.env.NEXT_PUBLIC_LIVE_STREAMING_TIME || "00:00",
        link: process.env.NEXT_PUBLIC_LIVE_STREAMING_LINK || "#",
        detail: process.env.NEXT_PUBLIC_LIVE_STREAMING_DETAIL || "Default Livestreaming Detail",
    },
    prewedding: {
        enabled: process.env.NEXT_PUBLIC_PREWEDDING === 'true',
        link: process.env.NEXT_PUBLIC_PREWEDDING_CODE_LINK_EMBED || "#",
        detail: process.env.NEXT_PUBLIC_PREWEDDING_DETAIL || "Default Prewedding Detail",
    },
    rsvp: {
        enabled: process.env.NEXT_PUBLIC_RSVP === 'true',
        detail: process.env.NEXT_PUBLIC_RSVP_DETAIL || "Default RSVP Detail",
    },
    thankyou: process.env.NEXT_PUBLIC_THANKYOU || "Default Thank You",
    thankyouDetail: process.env.NEXT_PUBLIC_THANKYOU_DETAIL || "Default Thank You Detail",
};
